// Generated by gencpp from file ki_robotics/Num.msg
// DO NOT EDIT!


#ifndef KI_ROBOTICS_MESSAGE_NUM_H
#define KI_ROBOTICS_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ki_robotics
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : header()
    , a(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , a(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::ki_robotics::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ki_robotics::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::ki_robotics::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::ki_robotics::Num > NumPtr;
typedef boost::shared_ptr< ::ki_robotics::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ki_robotics::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ki_robotics::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ki_robotics::Num_<ContainerAllocator1> & lhs, const ::ki_robotics::Num_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ki_robotics::Num_<ContainerAllocator1> & lhs, const ::ki_robotics::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ki_robotics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ki_robotics::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ki_robotics::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ki_robotics::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ki_robotics::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ki_robotics::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ki_robotics::Num_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ki_robotics::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b55c13cdbfddf5153ade99bfba91ab4";
  }

  static const char* value(const ::ki_robotics::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b55c13cdbfddf51ULL;
  static const uint64_t static_value2 = 0x53ade99bfba91ab4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ki_robotics::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ki_robotics/Num";
  }

  static const char* value(const ::ki_robotics::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ki_robotics::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 a\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ki_robotics::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ki_robotics::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ki_robotics::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ki_robotics::Num_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KI_ROBOTICS_MESSAGE_NUM_H
